# Generated by Django 3.0.2 on 2021-10-30 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timerr', '0003_auto_20211030_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='excersises',
            name='id',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='excersises',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
